### ISSUE TITLE
Error when tried to save a Note in Collection group

### ISSUE THREAD

**Issue by eroma2014** [SciGaP/emcenter-gateway#16]
Created a collection group as an
<img width="1776" alt="Screen Shot 2021-08-09 at 2 32 21 PM" src="https://user-images.githubusercontent.com/7841259/128756377-882f5308-f6a8-4863-bee1-f865f6ce74dc.png">
 Owner of a collection. Tried to add a Note and save it for the collection group. It did not get saved and the page kind of froze. Exceptions thrown.

**Comment by isururanawaka** [comment]
fixed with https://github.com/apache/airavata-data-lake/pull/38
