### ISSUE TITLE
Didn't share my files or collections with anyone but 'Shared by Me' shows collections and files as shared

### ISSUE THREAD

**Issue by eroma2014** [SciGaP/emcenter-gateway#17]
I logged in to the EMC portal as an Owner of multiple collections.
In 'Shared by Me' page, all my collections are listed and when i click share icon, it shows only myself and Isuru as owners.

Even though nothing is shared, all are listed as shared by Me.
<img width="1784" alt="Screen Shot 2021-08-09 at 2 36 09 PM" src="https://user-images.githubusercontent.com/7841259/128756931-7ea3bef1-d806-4e75-9013-fbf4b8b53d0d.png">

**Comment by isururanawaka** [comment]
Fixed with this https://github.com/apache/airavata-data-lake/pull/39 .  Please reopen if there are any related issues
