### ISSUE TITLE
When logged in a file is been shared with me but I am not in the shared list

### ISSUE THREAD

**Issue by eroma2014** [SciGaP/emcenter-gateway#19]
1. A single file is shared with me by Isuru. Its listed in 'My collections'.  When clicked the share button in the list, my name is not listed.
2. But, in 'Shared with Me' UI, there is a whole list of files shared with me by Isuru but here also my name is not listed when i click the Share icon.

<img width="1784" alt="Screen Shot 2021-08-09 at 2 56 57 PM" src="https://user-images.githubusercontent.com/7841259/128759605-f3b6e5d7-a412-42f8-bb20-3218b7ed7b54.png">
<img width="1790" alt="Screen Shot 2021-08-09 at 2 58 26 PM" src="https://user-images.githubusercontent.com/7841259/128759596-b37d32d7-c616-4895-8c8e-efd6d6b3ce68.png">

**Comment by isururanawaka** [comment]
This should resolved with https://github.com/apache/airavata-data-lake/pull/41 please reopen if having any issues
